name: Build packages
on:
  workflow_dispatch:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
    branches:
      - master
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    strategy:
      matrix:
        debian_version: [12, 13]
    steps:
      - name: Get version
        run: |
          if [[ "$GITHUB_REF_TYPE" == "tag" ]]; then
            echo "VERSION=${GITHUB_REF_NAME#v}" >> $GITHUB_ENV
          else
            echo "VERSION=0.0.0" >> $GITHUB_ENV
          fi
      - uses: earthly/actions-setup@v1
      - uses: actions/checkout@v5
      - name: Build
        run: earthly +build --VERSION=$VERSION --DEBIAN_VERSION=${{ matrix.debian_version }}
      - uses: actions/upload-artifact@v4
        with:
          name: debs-debian${{ matrix.debian_version }}
          path: out/*deb
  release:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
    permissions:
      contents: write
    steps:
      - uses: actions/download-artifact@v5
        with:
          path: release
          merge-multiple: true
      - uses: softprops/action-gh-release@v2
        with:
          draft: true
          files: release/*
